language: php

env:
  global:
    - APPLICATION_ENV=devtest
    - APPLICATION_STORE=DE
    - PROJECT=demoshop
    - MODULE_DIR=module
    - SHOP_DIR=current
    - MODULE_NAME=tideways

#Possible travis events (push, pull_request, cron, or api)
matrix:
  fast_finish: true
  include:
     - php: "7.1"
       env:
          - TEST_GROUP=without-acceptance
          - ON_EVENTS=cron,push
          - PHPSTAN=1
     - php: "7.2"
       env:
          - TEST_GROUP=without-acceptance
          - ON_EVENTS=cron,push
          - DB=mysql
     - php: "7.1"
       env:
          - TEST_GROUP=acceptance
          - ON_EVENTS=push,cron
     - php: "7.2"
       env:
          - TEST_GROUP=acceptance
          - ON_EVENTS=push,cron
          - DB=mysql

addons:
  postgresql: 9.6
  mysql: 5.7

  apt:
    packages:
      - graphviz

  hosts:
    - zed.de.spryker.test
    - www.de.spryker.test

cache:
  directories:
    - $HOME/.composer/cache

services:
  - postgresql
  - mysql
  - redis
  - rabbitmq

sudo: required

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - git clone -b '0.1.1' --single-branch https://github.com/spryker-eco/eco-ci.git ecoci
  - ./ecoci/build/travis.sh

notifications:
  email: false
